Feature/crcl 1971 data deletion schedule
Collectif-Recolte/allotomat pull request #209
Opened 2024-12-03 15:31 UTC by joc-sigmund

[Mettre en place les règles du calendrier d'entreposage et de suppression des données](https://sigmund-ca.atlassian.net/browse/CRCL-1971)

2024-12-04 22:14 UTC, ericforgues requested changes

2024-12-04 22:14 UTC, ericforgues commented on Sig.App.Backend/BackgroundJobs/DeleteBeneficiary.cs
> +            var beneficiaries = await db.Beneficiaries
Est-ce qu'il peut avoir beaucoup de beneficiaries, genre assez pour que ça plante? 
Est-ce qu'on fait des batchs?

2024-12-04 22:14 UTC, ericforgues commented on Sig.App.Backend/BackgroundJobs/DeleteUser.cs
> +            var usersToDelete = await db.Users.Include(x => x.Profile)
Meme chose ici, un risque d'en avoir vrmt bcp? Mieux faire des batches?

2024-12-04 22:14 UTC, ericforgues commented on Sig.App.Backend/BackgroundJobs/DeleteUser.cs
> +                foreach (var transactionLog in transactionLogsToAnonymized)
Il peut srmt avoir bcp de user qui ont bcp de transaction, je sais pas si ce serait bien de rajouter une couche pour s'assurer que ça plante pas, quitte a en faire juste une partie et que la job du lendemain complète.

Idée: Mettre un max de user, faire de transaction sql pour s'assurer de delete un user complet a chaque fois et ne pas le faire à moitié (genre un user delete mais qui a des transaction log pas encore anonumized.

2024-12-05 16:24 UTC, joc-sigmund commented on Sig.App.Backend/BackgroundJobs/DeleteUser.cs
> +                foreach (var transactionLog in transactionLogsToAnonymized)
J'ai fait une validation et ce n'est pas si pire étant donné qu'il y a seulement 350 utilisateurs actuellement.

Concernant les transactions, ce n'est pas si pire non plus puisqu'on mets anonymized seulement les transactions manuellement créer par l'utilisateur et non les transactions fait chez un marchand.

C'est extrêmement rare comme cas, donc ça ne me stress pas comme tâche.

2024-12-05 16:26 UTC, merged